[package]
name = "randsample"
version = "0.1.0"
authors = ["Jasen Borisov <jamadazi@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
rand = "0.7.3"
